AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 Lambda - org.example::gm-face-match-engine-lambda

Resources:
  GmFaceMatchEngineLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.gm.facematch.engine.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - SQSPollerPolicy:
            QueueName: gm-face-match-request-queue
        - S3ReadPolicy:
            BucketName: awoyomibucketdemo
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: https://sqs.us-east-1.amazonaws.com/980382773047/gm-face-match-request-queue
            BatchSize: 5

Outputs:
  GmFaceMatchEngineLambdaArn:
    Description: ARN of the Lambda function
    Value: !GetAtt GmFaceMatchEngineLambdaFunction.Arn
    Export:
      Name: GmFaceMatchEngineLambdaArn
